import {afterEach,describe,expect,test} from "bun:test";
import {mkdtemp,rm} from "node:fs/promises";import {join} from "node:path";import {tmpdir} from "node:os";
import {DurableCanvasService} from "../src/services/canvas/durable-canvas-service";import {FileCanvasRepository} from "../src/adapters/persistence/file-canvas-repository";import {FileRuntimeRepository} from "../src/adapters/runtime/file-runtime-repository";import {DeterministicRendererAdapter} from "../src/adapters/runtime/deterministic-renderer";import {ActivationRuntimeService} from "../src/runtime/runtime-service";import {projectDocument,scaleLogicalCanvas} from "../src/runtime/projection";
const dirs:string[]=[];afterEach(async()=>Promise.all(dirs.splice(0).map(x=>rm(x,{recursive:true,force:true}))));async function setup(options={}){const root=await mkdtemp(join(tmpdir(),"glansk-p3-"));dirs.push(root);const canvases=new DurableCanvasService(new FileCanvasRepository(root));const draft=await canvases.create({id:"display",name:"Display",logicalSize:{width:1280,height:720}});await canvases.save({document:{...draft.document,widgets:[{id:"title",packageId:"core",widgetId:"text",geometry:{x:10,y:20,width:200,height:80,zIndex:0},config:{text:"Hello"}}]},expectedDraftRevision:1});await canvases.publish("display");const renderer=new DeterministicRendererAdapter(options),runtime=new ActivationRuntimeService(canvases,new FileRuntimeRepository(root),renderer);return{root,canvases,renderer,runtime}}
describe("phase 3 runtime activation",()=>{
test("projects preview/live through one boundary and scales fixed canvas",async()=>{const {canvases}=await setup();const published=(await canvases.getPublished("display"))!;const themed={...published.document,theme:{preset:"aurora",variables:{"--canvas-accent":"#53e0bc"}}};const a=await projectDocument(themed,published.revision),b=await projectDocument(themed,published.revision);expect(a.digest).toBe(b.digest);expect(a.theme).toEqual(themed.theme);expect(a.widgets[0]?.sandbox).toBe("allow-scripts");expect(scaleLogicalCanvas({width:1280,height:720},{width:1920,height:1080})).toEqual({scale:1.5,offsetX:0,offsetY:0})});
test("atomically activates, is idempotent, and rejects stale revisions",async()=>{const {runtime,renderer}=await setup();expect((await runtime.activate({canvasId:"display",expectedActiveRevision:0,publicationRevision:1})).activeRevision).toBe(1);expect((await runtime.activate({canvasId:"display",expectedActiveRevision:1,publicationRevision:1})).generation).toBe(1);expect(renderer.starts).toHaveLength(1);expect(runtime.activate({canvasId:"display",expectedActiveRevision:0})).rejects.toMatchObject({code:"revision_conflict"})});
test("failed candidate preserves active last-known-good",async()=>{const {canvases,runtime}=await setup({failRevisions:[2]});await runtime.activate({canvasId:"display"});const open=(await canvases.open("display"))!;await canvases.save({document:{...open.draft.document,background:"#123456"},expectedDraftRevision:open.draft.draftRevision});await canvases.publish("display");expect(runtime.activate({canvasId:"display",publicationRevision:2})).rejects.toMatchObject({code:"malformed"});expect(await runtime.status("display")).toMatchObject({activeRevision:1,lastKnownGoodRevision:1,phase:"degraded"})});
test("restart recovers durable activation and reports status",async()=>{const {root,canvases,runtime}=await setup();await runtime.activate({canvasId:"display"});await runtime.shutdown();const renderer=new DeterministicRendererAdapter(),restarted=new ActivationRuntimeService(canvases,new FileRuntimeRepository(root),renderer);await restarted.initialize();expect(await restarted.status("display")).toMatchObject({phase:"ready",activeRevision:1,generation:2,restartCount:1});expect(await restarted.list()).toHaveLength(1)});
test("rollback is safe and restart budget is bounded",async()=>{const {runtime}=await setup();await runtime.activate({canvasId:"display"});expect((await runtime.rollback("display",1)).activeRevision).toBe(1);await runtime.restart("display");await runtime.restart("display");await runtime.restart("display");expect(runtime.restart("display")).rejects.toMatchObject({code:"forbidden"})});
test("deactivates running display runtime and transitions phase to inactive",async()=>{const {runtime,renderer}=await setup();await runtime.activate({canvasId:"display"});expect((await runtime.status("display")).phase).toBe("ready");const stopped=await runtime.deactivate("display");expect(stopped.phase).toBe("inactive");expect(stopped.lastKnownGoodRevision).toBe(1);expect(stopped.activeRevision).toBeUndefined();expect((await runtime.status("display")).phase).toBe("inactive");expect(renderer.stops).toHaveLength(1)});
test("rolls back to explicit historical target revision",async()=>{const {canvases,runtime}=await setup();await runtime.activate({canvasId:"display"});const open=(await canvases.open("display"))!;await canvases.save({document:{...open.draft.document,name:"Display V2"},expectedDraftRevision:open.draft.draftRevision});await canvases.publish("display");await runtime.activate({canvasId:"display",publicationRevision:2});expect((await runtime.status("display")).activeRevision).toBe(2);const rolled=await runtime.rollback("display",{targetRevision:1});expect(rolled.activeRevision).toBe(1);expect((await runtime.status("display")).activeRevision).toBe(1)});
});

