import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { FileCanvasRepository } from "../src/adapters/persistence/file-canvas-repository";
import { DurableCanvasService } from "../src/services/canvas/durable-canvas-service";
import { addComponent, createEditorSession, moveLayer, redo, selectWidget, undo, updateSelectedConfig, updateSelectedGeometry } from "../src/editor/session";
import { componentCatalog } from "../src/editor/catalog";
const directories:string[]=[];
async function service(){const root=await mkdtemp(join(tmpdir(),"glansk-phase2-"));directories.push(root);return{root,value:new DurableCanvasService(new FileCanvasRepository(root))}}
afterEach(async()=>{await Promise.all(directories.splice(0).map(path=>rm(path,{recursive:true,force:true})))});
describe("durable canvas repository",()=>{
 test("survives restart and keeps publications separate",async()=>{const {root,value}=await service();const created=await value.create({id:"lobby",name:"Lobby"});await value.save({document:{...created.document,background:"#fff"},expectedDraftRevision:1});const published=await value.publish("lobby");const restarted=new DurableCanvasService(new FileCanvasRepository(root));expect((await restarted.open("lobby"))?.draft.draftRevision).toBe(2);await restarted.save({document:{...published.document,background:"#000"},expectedDraftRevision:2});expect((await restarted.getPublished("lobby"))?.document.background).toBe("#fff")});
 test("rejects concurrent repository and stale draft writes",async()=>{const {root,value}=await service();const draft=await value.create({id:"desk",name:"Desk"});const other=new DurableCanvasService(new FileCanvasRepository(root));await other.save({document:draft.document,expectedDraftRevision:1});expect(value.save({document:draft.document,expectedDraftRevision:1})).rejects.toMatchObject({code:"revision_conflict"});const repository=new FileCanvasRepository(root),a=await repository.load(),b=await repository.load();await repository.commit(a.storeRevision,{schemaVersion:2,drafts:a.drafts,publications:a.publications});expect(repository.commit(b.storeRevision,{schemaVersion:2,drafts:b.drafts,publications:b.publications})).rejects.toMatchObject({code:"revision_conflict"})});
 test("migrates schema one and recovers a corrupt primary from backup",async()=>{const {root}=await service();await writeFile(join(root,"canvases.json"),JSON.stringify({schemaVersion:1,drafts:{},publications:{}}));const repository=new FileCanvasRepository(root);expect((await repository.load()).schemaVersion).toBe(2);const canvasService=new DurableCanvasService(repository);await canvasService.create({id:"one",name:"One"});await canvasService.save({document:(await canvasService.open("one"))!.draft.document,expectedDraftRevision:1});await writeFile(join(root,"canvases.json"),"broken");expect((await new FileCanvasRepository(root).load()).drafts.one).toBeDefined();expect(await readFile(join(root,"canvases.json"),"utf8")).toContain('"schemaVersion": 2')});
});
describe("editor depth",()=>{test("adds typed components, snaps edits, changes properties/layers and supports history",()=>{const document={schemaVersion:1 as const,id:"x",name:"X",logicalSize:{width:800,height:480},background:"#000",widgets:[]};let state=createEditorSession(document);state=addComponent(state,componentCatalog[0]!);const id=state.selectedWidgetId!;state=updateSelectedGeometry(state,{x:19,y:21,width:101});expect(state.document.widgets[0]?.geometry).toMatchObject({x:16,y:24,width:104});state=updateSelectedConfig(state,"text","Hello");state=addComponent(state,componentCatalog[1]!);state=selectWidget(state,id);state=moveLayer(state,1);expect(state.document.widgets.find(w=>w.id===id)?.geometry.zIndex).toBe(1);const undone=undo(state);expect(undone.document.widgets.find(w=>w.id===id)?.geometry.zIndex).toBe(0);expect(redo(undone).document.widgets.find(w=>w.id===id)?.geometry.zIndex).toBe(1);expect(state.dirty).toBe(true);expect(Object.keys(state.document)).not.toContain("selectedWidgetId")})});
