import type { CanvasDocument, JsonValue, WidgetInstance } from "../domain/types";
import type { ComponentDefinition } from "./catalog";
import { instantiateComponent } from "./catalog";
export type EditorTool = "select" | "pan";
export interface EditorSession { readonly document:CanvasDocument; readonly selectedWidgetId?:string; readonly tool:EditorTool; readonly zoom:number; readonly dirty:boolean; readonly past:readonly CanvasDocument[]; readonly future:readonly CanvasDocument[]; }
export function createEditorSession(document:CanvasDocument):EditorSession{return{document:structuredClone(document),tool:"select",zoom:1,dirty:false,past:[],future:[]}}
export function selectWidget(state:EditorSession,id:string|undefined):EditorSession{if(id&&!state.document.widgets.some(w=>w.id===id))return state;if(id)return{...state,selectedWidgetId:id};const next={...state};delete(next as {selectedWidgetId?:string}).selectedWidgetId;return next}
export function setTool(state:EditorSession,tool:EditorTool):EditorSession{return{...state,tool}}
export function setZoom(state:EditorSession,zoom:number):EditorSession{return{...state,zoom:Math.min(2,Math.max(.25,zoom))}}
function change(state:EditorSession,document:CanvasDocument,selectedWidgetId=state.selectedWidgetId):EditorSession{return{...state,document,past:[...state.past,structuredClone(state.document)].slice(-100),future:[],dirty:true,...(selectedWidgetId?{selectedWidgetId}:{})}}
const snap=(value:number,grid:number)=>Math.round(value/grid)*grid;
export function updateSelectedGeometry(state:EditorSession,patch:Partial<WidgetInstance["geometry"]>,grid=8):EditorSession{if(!state.selectedWidgetId)return state;const widgets=state.document.widgets.map(w=>{if(w.id!==state.selectedWidgetId)return w;const geometry={...w.geometry,...patch};geometry.x=Math.max(0,snap(geometry.x,grid));geometry.y=Math.max(0,snap(geometry.y,grid));geometry.width=Math.max(grid,snap(geometry.width,grid));geometry.height=Math.max(grid,snap(geometry.height,grid));geometry.x=Math.min(geometry.x,state.document.logicalSize.width-geometry.width);geometry.y=Math.min(geometry.y,state.document.logicalSize.height-geometry.height);return{...w,geometry}});return change(state,{...state.document,widgets})}
export function updateSelectedConfig(state:EditorSession,key:string,value:JsonValue):EditorSession{if(!state.selectedWidgetId)return state;return change(state,{...state.document,widgets:state.document.widgets.map(w=>w.id===state.selectedWidgetId?{...w,config:{...w.config,[key]:value}}:w)})}
export function addComponent(state:EditorSession,definition:ComponentDefinition):EditorSession{let suffix=1,id=definition.widgetId;while(state.document.widgets.some(w=>w.id===id))id=`${definition.widgetId}-${++suffix}`;const zIndex=Math.max(-1,...state.document.widgets.map(w=>w.geometry.zIndex))+1;const widget=instantiateComponent(definition,id,16,16,zIndex);return change(state,{...state.document,widgets:[...state.document.widgets,widget]},id)}
export function moveLayer(state:EditorSession,direction:-1|1):EditorSession{if(!state.selectedWidgetId)return state;const ordered=[...state.document.widgets].sort((a,b)=>a.geometry.zIndex-b.geometry.zIndex),index=ordered.findIndex(w=>w.id===state.selectedWidgetId),swap=index+direction;if(swap<0||swap>=ordered.length)return state;[ordered[index],ordered[swap]]=[ordered[swap]!,ordered[index]!];return change(state,{...state.document,widgets:ordered.map((w,zIndex)=>({...w,geometry:{...w.geometry,zIndex}}))})}
export function undo(state:EditorSession):EditorSession{const document=state.past.at(-1);if(!document)return state;return{...state,document:structuredClone(document),past:state.past.slice(0,-1),future:[structuredClone(state.document),...state.future],dirty:true}}
export function redo(state:EditorSession):EditorSession{const [document,...future]=state.future;if(!document)return state;return{...state,document:structuredClone(document),past:[...state.past,structuredClone(state.document)],future,dirty:true}}
export function markSaved(state:EditorSession):EditorSession{return{...state,dirty:false}}
